import {
  AuditEntry,
  DashboardStats,
  Evidence,
  InspectionTask,
  Location,
  RiskCase,
  User,
  Work,
} from "../types";

export const mockUser: User = {
  id: "u-101",
  full_name: "Ananya Krishnan",
  email: "ananya.krishnan@nigraani.gov.in",
  role: "auditor",
  agency_id: "ag-04",
  agency_name: "State Vigilance & Works Directorate",
};

const loc = (district: string, state: string, lat: number, lng: number): Location => ({
  id: `loc-${district.toLowerCase().replace(/\s/g, "-")}`,
  district,
  state,
  latitude: lat,
  longitude: lng,
});

export const mockLocations: Location[] = [
  loc("Kohima", "Nagaland", 25.6751, 94.1086),
  loc("Dibrugarh", "Assam", 27.4728, 94.912),
  loc("Imphal East", "Manipur", 24.817, 93.9368),
  loc("Shillong", "Meghalaya", 25.5788, 91.8933),
  loc("Coimbatore", "Tamil Nadu", 11.0168, 76.9558),
  loc("Guwahati", "Assam", 26.1445, 91.7362),
  loc("Aizawl", "Mizoram", 23.7271, 92.7176),
];

export const mockWorks: Work[] = [
  {
    id: "w-2201",
    title: "Rural Link Road — Zubza to Chiechama",
    work_code: "NL/RD/2201",
    agency_id: "ag-11",
    agency_name: "PWD Kohima Division",
    location: mockLocations[0],
    sanctioned_amount: 48200000,
    spent_amount: 41750000,
    start_date: "2025-02-10",
    expected_completion: "2026-03-31",
    status: "delayed",
    progress_pct: 61,
  },
  {
    id: "w-2202",
    title: "Primary Health Centre Upgrade, Naharlagun",
    work_code: "AR/HC/1187",
    agency_id: "ag-07",
    agency_name: "Directorate of Health Infrastructure",
    location: mockLocations[1],
    sanctioned_amount: 21500000,
    spent_amount: 19800000,
    start_date: "2025-05-01",
    expected_completion: "2026-01-15",
    status: "in_progress",
    progress_pct: 78,
  },
  {
    id: "w-2203",
    title: "Flood Embankment Reinforcement, Imphal River",
    work_code: "MN/FL/0093",
    agency_id: "ag-14",
    agency_name: "Water Resources Department",
    location: mockLocations[2],
    sanctioned_amount: 96000000,
    spent_amount: 88400000,
    start_date: "2024-11-20",
    expected_completion: "2025-10-30",
    status: "stalled",
    progress_pct: 44,
  },
  {
    id: "w-2204",
    title: "Govt. Higher Secondary School Building, Shillong",
    work_code: "ML/ED/0442",
    agency_id: "ag-09",
    agency_name: "Education Infrastructure Board",
    location: mockLocations[3],
    sanctioned_amount: 33750000,
    spent_amount: 12300000,
    start_date: "2025-08-05",
    expected_completion: "2026-08-05",
    status: "in_progress",
    progress_pct: 22,
  },
  {
    id: "w-2205",
    title: "Guwahati Ring Road — Package 4",
    work_code: "AS/RD/3311",
    agency_id: "ag-02",
    agency_name: "PWD Guwahati Metro Division",
    location: mockLocations[5],
    sanctioned_amount: 187000000,
    spent_amount: 179500000,
    start_date: "2024-06-01",
    expected_completion: "2025-12-31",
    status: "delayed",
    progress_pct: 83,
  },
];

export const mockRiskCases: RiskCase[] = [
  {
    id: "rc-8841",
    case_number: "NG-2026-08841",
    work_id: "w-2203",
    work_title: "Flood Embankment Reinforcement, Imphal River",
    work_code: "MN/FL/0093",
    agency_name: "Water Resources Department",
    location: mockLocations[2],
    risk_level: "critical",
    risk_score: 91,
    status: "escalated",
    flagged_at: "2026-08-14T09:22:00Z",
    assigned_to: "Ananya Krishnan",
    sanctioned_amount: 96000000,
    spent_amount: 88400000,
    summary:
      "Expenditure at 92% of sanctioned amount against 44% physical progress. Third-party geotagged inspection contradicts contractor progress claims.",
    signals: [
      { id: "s1", label: "Expenditure–progress mismatch", detail: "48 point gap between fund utilisation and verified progress", weight: 38 },
      { id: "s2", label: "Duplicate billing pattern", detail: "Two invoices reference the same material consignment number", weight: 27 },
      { id: "s3", label: "Site inactivity", detail: "No machinery movement detected at site for 19 days", weight: 26 },
    ],
  },
  {
    id: "rc-8839",
    case_number: "NG-2026-08839",
    work_id: "w-2201",
    work_title: "Rural Link Road — Zubza to Chiechama",
    work_code: "NL/RD/2201",
    agency_name: "PWD Kohima Division",
    location: mockLocations[0],
    risk_level: "high",
    risk_score: 74,
    status: "under_review",
    flagged_at: "2026-08-20T14:05:00Z",
    assigned_to: "Ananya Krishnan",
    sanctioned_amount: 48200000,
    spent_amount: 41750000,
    summary:
      "Cost overrun trajectory exceeds sanctioned ceiling by projected completion. Two prior extension requests on record.",
    signals: [
      { id: "s1", label: "Cost overrun trajectory", detail: "Projected to exceed sanction by 14% at current burn rate", weight: 41 },
      { id: "s2", label: "Repeated timeline extension", detail: "Second extension request filed within 6 months", weight: 33 },
    ],
  },
  {
    id: "rc-8825",
    case_number: "NG-2026-08825",
    work_id: "w-2205",
    work_title: "Guwahati Ring Road — Package 4",
    work_code: "AS/RD/3311",
    agency_name: "PWD Guwahati Metro Division",
    location: mockLocations[5],
    risk_level: "medium",
    risk_score: 52,
    status: "open",
    flagged_at: "2026-08-25T11:40:00Z",
    sanctioned_amount: 187000000,
    spent_amount: 179500000,
    summary: "Material quality test report pending beyond the 30-day compliance window.",
    signals: [
      { id: "s1", label: "Overdue quality report", detail: "Aggregate test report overdue by 11 days", weight: 30 },
      { id: "s2", label: "Vendor concentration", detail: "84% of contracts under this work awarded to a single supplier", weight: 22 },
    ],
  },
  {
    id: "rc-8801",
    case_number: "NG-2026-08801",
    work_id: "w-2204",
    work_title: "Govt. Higher Secondary School Building, Shillong",
    work_code: "ML/ED/0442",
    agency_name: "Education Infrastructure Board",
    location: mockLocations[3],
    risk_level: "low",
    risk_score: 28,
    status: "resolved",
    flagged_at: "2026-07-30T08:12:00Z",
    assigned_to: "Rahul Mehta",
    sanctioned_amount: 33750000,
    spent_amount: 12300000,
    summary: "Minor documentation gap in labour compliance filing — resolved with updated submission.",
    signals: [
      { id: "s1", label: "Documentation gap", detail: "Labour compliance certificate filed 6 days late", weight: 18 },
    ],
  },
  {
    id: "rc-8790",
    case_number: "NG-2026-08790",
    work_id: "w-2202",
    work_title: "Primary Health Centre Upgrade, Naharlagun",
    work_code: "AR/HC/1187",
    agency_name: "Directorate of Health Infrastructure",
    location: mockLocations[1],
    risk_level: "medium",
    risk_score: 47,
    status: "open",
    flagged_at: "2026-08-27T16:50:00Z",
    sanctioned_amount: 21500000,
    spent_amount: 19800000,
    summary: "Utilisation rate outpacing physical milestones by a moderate margin.",
    signals: [
      { id: "s1", label: "Milestone lag", detail: "Two billed milestones lack corresponding inspection sign-off", weight: 29 },
    ],
  },
];

export const mockEvidence: Evidence[] = [
  { id: "ev-1", case_id: "rc-8841", type: "geotag", title: "Site visit — embankment section B", submitted_by: "Field Inspector, WRD", submitted_at: "2026-08-13T10:00:00Z", reference: "GEO-4471", verified: true },
  { id: "ev-2", case_id: "rc-8841", type: "financial", title: "Invoice pair — consignment #MC-1182", submitted_by: "Finance Cell", submitted_at: "2026-08-14T09:00:00Z", reference: "FIN-9903", verified: true },
  { id: "ev-3", case_id: "rc-8841", type: "photo", title: "Aerial survey, 12 Aug", submitted_by: "Drone Survey Unit", submitted_at: "2026-08-12T07:30:00Z", reference: "IMG-3390", verified: false },
  { id: "ev-4", case_id: "rc-8841", type: "document", title: "Contractor progress declaration", submitted_by: "M/s Highline Infra", submitted_at: "2026-08-10T12:00:00Z", reference: "DOC-1290", verified: true },
  { id: "ev-5", case_id: "rc-8839", type: "financial", title: "Cost overrun projection sheet", submitted_by: "Finance Cell", submitted_at: "2026-08-19T15:20:00Z", reference: "FIN-9884", verified: true },
  { id: "ev-6", case_id: "rc-8839", type: "statement", title: "Extension request — round 2", submitted_by: "PWD Kohima Division", submitted_at: "2026-08-18T11:10:00Z", reference: "DOC-1244", verified: true },
];

export const mockAuditTrail: AuditEntry[] = [
  { id: "a-1", actor: "Ananya Krishnan", actor_role: "auditor", action: "escalated_case", entity_type: "risk_case", entity_ref: "NG-2026-08841", timestamp: "2026-08-31T09:14:00Z", detail: "Escalated to state vigilance unit citing duplicate billing pattern.", ip_address: "10.42.6.113" },
  { id: "a-2", actor: "Rahul Mehta", actor_role: "inspector", action: "submitted_evidence", entity_type: "evidence", entity_ref: "GEO-4471", timestamp: "2026-08-30T17:02:00Z", detail: "Uploaded geotagged site inspection for embankment section B." },
  { id: "a-3", actor: "System", actor_role: "admin", action: "risk_score_recalculated", entity_type: "risk_case", entity_ref: "NG-2026-08839", timestamp: "2026-08-30T02:00:00Z", detail: "Nightly recomputation raised risk score from 68 to 74." },
  { id: "a-4", actor: "Priya Nair", actor_role: "admin", action: "assigned_case", entity_type: "risk_case", entity_ref: "NG-2026-08839", timestamp: "2026-08-29T13:45:00Z", detail: "Assigned case to Ananya Krishnan for review." },
  { id: "a-5", actor: "Ananya Krishnan", actor_role: "auditor", action: "resolved_case", entity_type: "risk_case", entity_ref: "NG-2026-08801", timestamp: "2026-08-05T10:30:00Z", detail: "Marked resolved after updated labour compliance filing received.", ip_address: "10.42.6.113" },
  { id: "a-6", actor: "System", actor_role: "admin", action: "case_flagged", entity_type: "risk_case", entity_ref: "NG-2026-08790", timestamp: "2026-08-27T16:50:00Z", detail: "Auto-flagged from monitoring pipeline: milestone lag threshold exceeded." },
  { id: "a-7", actor: "Vikram Singh", actor_role: "inspector", action: "scheduled_inspection", entity_type: "inspection", entity_ref: "INS-3312", timestamp: "2026-08-26T08:15:00Z", detail: "Scheduled field inspection for Guwahati Ring Road Package 4." },
];

export const mockInspections: InspectionTask[] = [
  {
    id: "ins-3312",
    case_id: "rc-8825",
    case_number: "NG-2026-08825",
    work_title: "Guwahati Ring Road — Package 4",
    location: mockLocations[5],
    scheduled_date: "2026-09-05",
    assigned_to: "Vikram Singh",
    priority: "medium",
    status: "scheduled",
    checklist: [
      { id: "c1", label: "Verify aggregate test certificates", done: false },
      { id: "c2", label: "Cross-check vendor invoices against site register", done: false },
      { id: "c3", label: "Photograph current progress markers", done: false },
    ],
  },
  {
    id: "ins-3298",
    case_id: "rc-8841",
    case_number: "NG-2026-08841",
    work_title: "Flood Embankment Reinforcement, Imphal River",
    location: mockLocations[2],
    scheduled_date: "2026-09-02",
    assigned_to: "Rahul Mehta",
    priority: "critical",
    status: "in_progress",
    checklist: [
      { id: "c1", label: "Re-verify embankment section B measurements", done: true },
      { id: "c2", label: "Interview site supervisor on machinery logs", done: true },
      { id: "c3", label: "Collect duplicate invoice originals", done: false },
      { id: "c4", label: "File findings to vigilance unit", done: false },
    ],
  },
  {
    id: "ins-3301",
    case_id: "rc-8839",
    case_number: "NG-2026-08839",
    work_title: "Rural Link Road — Zubza to Chiechama",
    location: mockLocations[0],
    scheduled_date: "2026-09-09",
    assigned_to: "Ananya Krishnan",
    priority: "high",
    status: "pending",
    checklist: [
      { id: "c1", label: "Review second extension justification", done: false },
      { id: "c2", label: "Validate revised cost projection", done: false },
    ],
  },
];

export const mockStats: DashboardStats = {
  total_works: 214,
  active_works: 156,
  open_cases: 37,
  critical_cases: 6,
  total_sanctioned: 4820000000,
  total_spent: 3610000000,
  flagged_amount: 412000000,
  resolution_rate: 0.72,
};
